[workspace]
resolver = "2"

members = [
    "arc_queue_pool",
    "arc_slice_pool",
    "breadcrumb_channel",
    "stable_queue",
]

[workspace.dependencies]
bitvec = "1.0.1"
consume_on_drop = "0.1.1"
derive-where = "1.2.7"
parking_lot = "0.12.3"
tokio = "1.38.0"
