[package]
name = "arc_queue_pool"
version = "0.1.0"
edition = "2021"

[dependencies]
consume_on_drop = "*"
derive-where = "*"
parking_lot = "*"

stable_queue = { path = "../stable_queue" }

[dev-dependencies]
bitvec = "*"
